id: IF1195FAE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T13:44:32+00:00'
last_modified: '2022-06-08T14:08:05.282859+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23882
  title: ཕ་བོང་ཁ་པའི་ཟིན་བྲིས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '5904':
      image_group_id: I1KG591
      title: ''
      total_pages: 582
      order: 1
      base_file: 5904.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
