id: P010511
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-19 20:53:29.936108
source_metadata:
  id: bdr:W23882
  title: ཕ་བོང་ཁ་པའི་ཟིན་བྲིས
  author: ''
  volumes:
    cae674cc0f69463986d27ba6fb4a98f7:
      image_group_id: I1KG591
      title: ''
      volume_number: 1
      total_pages: 582
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
